### ISSUE TITLE
프로젝트 초기 설정 및 공통 기능 추가

### ISSUE THREAD

**Issue by FaberJoo** [FaberJoo/twitter-clone#1]
## 📝 개요
프로젝트 초기 설정 및 공통 기능 추가

## ✅ TODO
- [x] 에러 코드 추가
- [x] 커스텀 예외 추가
- [x] 예외 응답 추가
- [x] 예외 핸들러 advice 추가
- [x] Slice 응답 추가
- [x] Page 응답 추가
- [x] 파라미터 스토어 설정 추가
- [x] db 설정 추가 
- [x] 기타 의존성 설정
- [x] 프로파일 설정 및 분리
